name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.2
  cupertino_icons: ^1.0.8
  collection: ^1.18.0          # Update collection
  http_parser: 4.0.2          # Update http_parser
  material_color_utilities: ^0.11.1  # Update material_color_utilities
  meta: ^1.15.0                # Update meta
  string_scanner: ^1.2.0       # Update string_scanner
  video_player: ^2.5.0  # Add the latest version here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0        # Update flutter_lints to latest version
  leak_tracker: ^10.0.5        # Update leak_tracker
  leak_tracker_flutter_testing: ^3.0.5  # Update leak_tracker_flutter_testing
  stack_trace: ^1.11.1         # Update stack_trace
  test_api: ^0.7.2             # Update test_api
  vm_service: ^14.2.5          # Update vm_service


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/video/